before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X 'github.com/antham/doc-hunt/file.appVersion={{.Version}}'
