language: go

go:
  - 1.6

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get github.com/Masterminds/glide

install: glide install

script:
  make run-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
