// Code generated by "stringer -type=ItemStatus"; DO NOT EDIT

package file

import "fmt"

const _ItemStatus_name = "INONEIFAILEDIADDEDIUPDATEDIDELETED"

var _ItemStatus_index = [...]uint8{0, 5, 12, 18, 26, 34}

func (i ItemStatus) String() string {
	if i < 0 || i >= ItemStatus(len(_ItemStatus_index)-1) {
		return fmt.Sprintf("ItemStatus(%d)", i)
	}
	return _ItemStatus_name[_ItemStatus_index[i]:_ItemStatus_index[i+1]]
}
