// Code generated by "stringer -type=SourceStatus"; DO NOT EDIT

package file

import "fmt"

const _SourceStatus_name = "FailedUntouchedUpdatedDeleted"

var _SourceStatus_index = [...]uint8{0, 6, 15, 22, 29}

func (i SourceStatus) String() string {
	if i < 0 || i >= SourceStatus(len(_SourceStatus_index)-1) {
		return fmt.Sprintf("SourceStatus(%d)", i)
	}
	return _SourceStatus_name[_SourceStatus_index[i]:_SourceStatus_index[i+1]]
}
